meta_product_name: "Code and Writing Portfolio"
meta_title: "Jessica's Portfolio"
meta_description: "View some of the projects I've worked on as a professional developer and writer. Contact me to discover more about what I can offer you and your organization."
meta_image: "portfolio-meta-img.jpg"
twitter_account: "@Opalevanescence"
